drop table DAYCARE_CENTER;
drop table KINDERGARTEN;
drop table PARK;
drop table HOSPITAL;
drop table SCHOOL;
drop table ART_MUSEUM;
drop table MUSEUM;
drop table KID_CAFE;
drop table RECOMMEND;

DROP SEQUENCE seq_care;
DROP SEQUENCE seq_park;
DROP SEQUENCE seq_hospt;
DROP SEQUENCE seq_sch;
DROP SEQUENCE seq_art;
DROP SEQUENCE seq_mus;
DROP SEQUENCE seq_cafe;
DROP SEQUENCE seq_kidgd;
DROP SEQUENCE seq_recommend;

CREATE SEQUENCE seq_care
START WITH 1
INCREMENT BY 1;

CREATE TABLE DAYCARE_CENTER (
CARE_SEQ NUMBER PRIMARY KEY,
CARE_NAME VARCHAR2(100) NOT NULL,
CARE_TYPE VARCHAR2(100) NOT NULL,
CARE_CHILD NUMBER(30) NOT NULL,
CARE_TEACHER NUMBER(30) NOT NULL,
CARE_OPERATION VARCHAR2(100) NOT NULL,
CARE_BUS VARCHAR2(30) NOT NULL,
CARE_BUILD VARCHAR2(100) NOT NULL,
CARE_CITY VARCHAR2(100) NOT NULL,
CARE_LOCAL VARCHAR2(100) NOT NULL,
CARE_ROAD VARCHAR2(100) NOT NULL,
CARE_AREA VARCHAR2(100) NOT NULL,
CARE_LAT VARCHAR2(100) NOT NULL,
CARE_LONG VARCHAR2(100) NOT NULL,
CARE_SCORE VARCHAR2(100) NOT NULL,
CARE_NEAR VARCHAR2(50));

CREATE SEQUENCE seq_kidgd
START WITH 1
INCREMENT BY 1;

CREATE TABLE KINDERGARTEN (
KIDGD_SEQ NUMBER PRIMARY KEY,
KIDGD_NAME VARCHAR2(50) NOT NULL,
KIDGD_CYPE VARCHAR2(30) NOT NULL,
KIDGD_KID NUMBER(30) NOT NULL,
KIDGD_TEACHER NUMBER(30) NOT NULL,
KIDGD_BUS VARCHAR2(30) NOT NULL,
KIDGD_BUILD VARCHAR2(30) NOT NULL,
KIDGD_OPERATION VARCHAR2(30) NOT NULL,
KIDGD_CITY VARCHAR2(30) NOT NULL,
KIDGD_LOCAL VARCHAR2(30) NOT NULL,
KIDGD_ROAD VARCHAR2(30) NOT NULL,
KIDGD_AREA VARCHAR2(20) NOT NULL,
KIDGD_LAT VARCHAR2(30) NOT NULL,
KIDGD_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_park
START WITH 1
INCREMENT BY 1;

CREATE TABLE PARK (
PARK_SEQ NUMBER PRIMARY KEY,
PARK_NAME VARCHAR2(50) NOT NULL,
PARK_TYPE VARCHAR2(30) NOT NULL,
PARK_CITY VARCHAR2(30) NOT NULL,
PARK_LOCAL VARCHAR2(30) NOT NULL,
PARK_AREA VARCHAR2(30) NOT NULL,
PARK_LAT VARCHAR2(30) NOT NULL,
PARK_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_hospt
START WITH 1
INCREMENT BY 1;

CREATE TABLE HOSPITAL (
HOSPT_SEQ NUMBER PRIMARY KEY,
HOSPT_NAME VARCHAR2(50) NOT NULL,
HOSPT_TYPE VARCHAR2(30) NOT NULL,
HOSPT_CITY VARCHAR2(30) NOT NULL,
HOSPT_LOCAL VARCHAR2(30) NOT NULL,
HOSPT_ROAD VARCHAR2(30) NOT NULL,
HOSPT_AREA VARCHAR2(30) NOT NULL,
HOSPT_LAT VARCHAR2(30) NOT NULL,
HOSPT_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_art
START WITH 1
INCREMENT BY 1;

CREATE TABLE ART_MUSEUM (
ART_SEQ NUMBER PRIMARY KEY,
ART_NAME VARCHAR2(50) NOT NULL,
ART_CITY VARCHAR2(30) NOT NULL,
ART_LOCAL VARCHAR2(30) NOT NULL,
ART_ROAD VARCHAR2(30) NOT NULL,
ART_AREA VARCHAR2(30) NOT NULL,
ART_LAT VARCHAR2(30) NOT NULL,
ART_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_mus
START WITH 1
INCREMENT BY 1;

CREATE TABLE MUSEUM (
MUS_SEQ NUMBER PRIMARY KEY,
MUS_NAME VARCHAR2(50) NOT NULL,
MUS_CITY VARCHAR2(30) NOT NULL,
MUS_LOCAL VARCHAR2(30) NOT NULL,
MUS_ROAD VARCHAR2(30) NOT NULL,
MUS_AREA VARCHAR2(30) NOT NULL,
MUS_LAT VARCHAR2(30) NOT NULL,
MUS_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_cafe
START WITH 1
INCREMENT BY 1;

CREATE TABLE KID_CAFE (
CAFE_SEQ NUMBER PRIMARY KEY,
CAFE_NAME VARCHAR2(50) NOT NULL,
CAFE_CITY VARCHAR2(30) NOT NULL,
CAFE_LOCAL VARCHAR2(30) NOT NULL,
CAFE_ROAD VARCHAR2(30) NOT NULL,
CAFE_AREA VARCHAR2(30) NOT NULL,
CAFE_LAT VARCHAR2(30) NOT NULL,
CAFE_LONG VARCHAR2(30) NOT NULL);

CREATE SEQUENCE seq_recommend
START WITH 1
INCREMENT BY 1;

CREATE TABLE RECOMMEND(
RCMEND_SEQ NUMBER PRIMARY KEY,
RCMEND_LOCAL VARCHAR2(50) NOT NULL,
RCMEND_ADDR VARCHAR2(300) NOT NULL,
RCMEND_LAT VARCHAR2(50) NOT NULL,
RCMEND_LONG VARCHAR2(50) NOT NULL,
RCMEND_TEACHER NUMBER NOT NULL);

select * from daycare_center
select * from RECOMMEND